### PR TITLE
added option conflict verification

### PR DESCRIPTION
**Pull request by 1Franck**

### CODE REVIEW

**Comment by c9s** [comment]
awesome

**Comment by 1Franck** [comment]
Thanks! Can you make a new release for those PR ?

**Comment by c9s** [comment]
Sure

François Lajoie <notifications@github.com>於 2017年6月30日 週五，22:41寫道：

**Comment by c9s** [comment]
2.5.5 is now released.

**Comment by c9s** [comment]
sorry because the PRs contains one conflict feature, I bumped the version to 2.6.0

**Comment by 1Franck** [comment]
no problem. thank you

**Pull request merged**
